# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.
#
# Google Play Store submission requirements:
# - Code must pass static analysis without critical errors
# - All warnings should be addressed for production builds
# - Lint rules help ensure code quality and maintainability

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated files and build outputs from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"
  
  # Enable stricter analysis for production builds
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing return statements as errors
    missing_return: error
    # Treat invalid assignment as errors
    invalid_assignment: error
    # Treat undefined class as errors
    undefined_class: error
    # Treat undefined method as errors
    undefined_method: error
    # Treat undefined operator as errors
    undefined_operator: error
    # Treat undefined getter as errors
    undefined_getter: error
    # Treat undefined setter as errors
    undefined_setter: error
    # Treat undefined variable as errors
    undefined_variable: error
    # Treat invalid_null_aware_operator as errors
    invalid_null_aware_operator: error
    # Treat dead_code as warnings (not errors, but should be reviewed)
    dead_code: warning

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Code quality rules (enabled for Google Play submission)
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    avoid_print: false  # Keep print for debugging (can be disabled in production)
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    use_key_in_widget_constructors: true
    # Performance rules
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    # Security rules
    avoid_web_libraries_in_flutter: true
    no_duplicate_case_values: true
    # Best practices
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_redundant_argument_values: true
    avoid_types_as_parameter_names: true
    no_leading_underscores_for_library_prefixes: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_operators: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_rethrow_when_possible: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
