package com.raidalarm.fake_call

object FakeCallConstants {
    const val ACTION_FAKE_CALL_INCOMING = "com.raidalarm.ACTION_FAKE_CALL_INCOMING"
    const val ACTION_FAKE_CALL_ACCEPT = "com.raidalarm.ACTION_FAKE_CALL_ACCEPT"
    const val ACTION_FAKE_CALL_DECLINE = "com.raidalarm.ACTION_FAKE_CALL_DECLINE"
    const val ACTION_FAKE_CALL_TIMEOUT = "com.raidalarm.ACTION_FAKE_CALL_TIMEOUT"
    
    const val EXTRA_FAKE_CALL_DATA = "EXTRA_FAKE_CALL_DATA"
    
    const val EXTRA_FAKE_CALL_ID = "EXTRA_FAKE_CALL_ID"
    const val EXTRA_FAKE_CALL_NAME_CALLER = "EXTRA_FAKE_CALL_NAME_CALLER"
    const val EXTRA_FAKE_CALL_NUMBER = "EXTRA_FAKE_CALL_NUMBER"
    const val EXTRA_FAKE_CALL_AVATAR = "EXTRA_FAKE_CALL_AVATAR"
    const val EXTRA_FAKE_CALL_DURATION = "EXTRA_FAKE_CALL_DURATION"
    const val EXTRA_FAKE_CALL_TEXT_ACCEPT = "EXTRA_FAKE_CALL_TEXT_ACCEPT"
    const val EXTRA_FAKE_CALL_TEXT_DECLINE = "EXTRA_FAKE_CALL_TEXT_DECLINE"
    const val EXTRA_FAKE_CALL_SUBTITLE = "EXTRA_FAKE_CALL_SUBTITLE"
    const val EXTRA_FAKE_CALL_MISSED_SUBTITLE = "EXTRA_FAKE_CALL_MISSED_SUBTITLE"
    const val EXTRA_FAKE_CALL_RINGTONE_PATH = "EXTRA_FAKE_CALL_RINGTONE_PATH"
    const val EXTRA_FAKE_CALL_BACKGROUND_IMAGE = "EXTRA_FAKE_CALL_BACKGROUND_IMAGE"
    const val EXTRA_FAKE_CALL_BACKGROUND_COLOR = "EXTRA_FAKE_CALL_BACKGROUND_COLOR"
    const val EXTRA_FAKE_CALL_ACTION_COLOR = "EXTRA_FAKE_CALL_ACTION_COLOR"
    const val EXTRA_FAKE_CALL_TEXT_COLOR = "EXTRA_FAKE_CALL_TEXT_COLOR"
    const val EXTRA_FAKE_CALL_APP_NAME = "EXTRA_FAKE_CALL_APP_NAME"
    
    const val NOTIFICATION_CHANNEL_ID_FAKE_CALL = "raidalarm_fake_call_channel"
    const val NOTIFICATION_ID_FAKE_CALL = 20000
}
