// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoluuxJk8W5a1l0Tp7Sj5Jkz639UrH8hA',
    appId: '1:1078914250757:web:aae8f2b43deeb28458c46c',
    messagingSenderId: '1078914250757',
    projectId: 'raidcapture-f3e05',
    authDomain: 'raidcapture-f3e05.firebaseapp.com',
    storageBucket: 'raidcapture-f3e05.firebasestorage.app',
    measurementId: 'G-GHB25THDN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuPXOP2n2d-abeqxGX24v57elyb-LQt0',
    appId: '1:1078914250757:android:c0dcad7e4c13b3f858c46c',
    messagingSenderId: '1078914250757',
    projectId: 'raidcapture-f3e05',
    storageBucket: 'raidcapture-f3e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQR8rWxkFzOQftBZ-lYrkTgPs4wT0zcls',
    appId: '1:1078914250757:ios:4be0fd14670988ce58c46c',
    messagingSenderId: '1078914250757',
    projectId: 'raidcapture-f3e05',
    storageBucket: 'raidcapture-f3e05.firebasestorage.app',
    iosBundleId: 'com.raidalarm',
  );
}
